version: "3.7"
services:

    worker_service:
        build:
          context: .
          dockerfile: ./Dockerfile        
        container_name: worker_service
        restart: unless-stopped
        environment: 
          ASPNETCORE_ENVIRONMENT: "Development"
        volumes:
          - ./container:/var/log
